### PR TITLE
modified exercises

### PR DESCRIPTION
**Pull request by Osei-b4**
I completed the exercises in the "2-dom-manipulation" section.

### CODE REVIEW

**Comment by bermarte** [comment]
Hi @Osei-b4 this PR should point to your fork, not to the one of HYFBE.

**Comment by sammou00** [comment]
@bermarte , there is no bug here, they should modify the dom using Js,  @Osei-b4  the exercises about dom manipulation, which means you need to use JS to pass the tests and not to change the `HTML`.

**Comment by Osei-b4** [comment]
oke i will get right on it thank you

**Comment by bermarte** [comment]
@samirm00 The PR was mistakenly directed to the HYFBE's repo instead of his own, but we also understood that we can't make a PR from a branch to the same one. It's important to clarify all this to the students, which in this case, I did; so I explained why you closed this PR and how eventually to fix it. Of course, what you wrote and did holds true. EDIT: I also asked for your review.

**Comment by bermarte** [comment]
@samirm00 Probably this is the same mistake.
 https://github.com/HackYourFutureBelgium/bf-separation-of-concerns/pull/1

**Pull request closed without merging**
